
services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: production
      MYSQL_ROOT_PASSWORD: Thuong221096
    # stop public port => can not public access
    # ports:
    #   - "3306:3306"

  web:
    build: .
    command: gunicorn ProductionManageBE.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    # stop public port => can not public access
    # ports: 
    #   - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:Thuong221096@db:3306/production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  mysql_data:
