# Generated by Django 5.0.4 on 2024-05-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=50, null=True)),
                ("updated_by", models.CharField(max_length=50, null=True)),
                ("cust_code", models.CharField(max_length=50, null=True)),
                ("cust_name", models.CharField(max_length=128, null=True)),
                ("cust_company", models.CharField(max_length=128, null=True)),
                ("cust_avatar", models.CharField(max_length=250, null=True)),
                ("cust_add", models.CharField(max_length=250, null=True)),
                ("payment_term", models.CharField(max_length=50, null=True)),
                ("email_address", models.CharField(max_length=50, null=True)),
                ("fax_no", models.CharField(max_length=50, null=True)),
                ("tel_no", models.CharField(max_length=50, null=True)),
                ("mobile_no", models.CharField(max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
