# Generated by Django 5.0.4 on 2024-05-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=50, null=True)),
                ("updated_by", models.CharField(max_length=50, null=True)),
                ("prod_code", models.CharField(max_length=20, null=True)),
                ("prod_fullname", models.CharField(max_length=255, null=True)),
                ("hash_code", models.CharField(max_length=55, null=True)),
                ("ingredient", models.CharField(max_length=20, null=True)),
                (
                    "exp",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                ("market", models.CharField(max_length=10, null=True)),
                ("prod_name", models.CharField(max_length=128, null=True)),
                ("label_path", models.CharField(max_length=255, null=True)),
                ("barcode", models.CharField(max_length=20, null=True)),
                ("delay_m4", models.CharField(max_length=20, null=True)),
                ("delay_m5", models.CharField(max_length=20, null=True)),
                (
                    "pack_size",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                ("loose_uom", models.CharField(max_length=10, null=True)),
                ("whole_uom", models.CharField(max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
